#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

api_login_check:
  path: /api/login_check

